{% set name = "sphinx-click" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 793c68b41c4a9435f953e2a27f9bf5883729037b7431f32b2776257c2966bd1b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
    - pbr >=2.0
  run:
    - python >=3.5
    - sphinx >=1.5,<3.0
test:
  imports:
    - sphinx_click

about:
  home: https://pypi.org/project/sphinx-click/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Sphinx plugin to automatically document click-based applications' 
  description: |
    sphinx-click is a Sphinx plugin that allows you to automatically extract 
    documentation from a click-based application and include it in your docs.
  doc_url: https://sphinx-click.readthedocs.io/en/latest/
  dev_url: https://github.com/click-contrib/sphinx-click

extra:
  recipe-maintainers:
    - CurtLH
    - williamjamir
