{% set name = "sphinx-click" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d4a5c5c90644f9100dd0b53dc64ba29164337b13360fcc9f28385561026f1b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - pbr >=2.0
  run:
    - python >=3.5
    - sphinx >=1.5,<4.0
    - click
    - pbr >=2.0
test:
  imports:
    - sphinx_click
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-click/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Sphinx plugin to automatically document click-based applications
  description: |
    sphinx-click is a Sphinx plugin that allows you to automatically extract 
    documentation from a click-based application and include it in your docs.
  doc_url: https://sphinx-click.readthedocs.io/en/latest/
  dev_url: https://github.com/click-contrib/sphinx-click

extra:
  recipe-maintainers:
    - CurtLH
    - williamjamir
