travis:
  secure:
    BINSTAR_TOKEN: dnQGmA/V/2aibO5BOjwSPEvCjDqX9+KmftdU+izFhEbBdMIDHZePc7XLUCrde2/uMNmqblgxaYVFL5Yj/LZy3VZJLod0W6a8ZP+kp0GyTpUu+qU009sJv9+0RTSUCrfcxbeetlMM0RA14tKuco7RBn9NdirY25nu/tyizpLGMXXGxYozq0JCTPgZ5HmgrLxk4Egtscxr+TUkKqnBRhObpTXh1Q9zC69XXbSajMzRRBoHMwgDKDhd6MgZ3/2RYL/nohSvhOd0G+8N7f5vjP0YdAxRy4YTQFQBI3KUgMk9al3C/vJ1WQSm080SJ/slc0Ze7K4Z0zi93ZMvq6bkZSDaDqWvmQGfnNUkcrVWPYtk2pAx4MnWxfsVdxyY/Wz0RCH5lMAQBXYsJEXODqlxZxP/aRtZldn5iSn5JT/t2As8RvU/8mN7RgGy/+KYwrBkKn8VU/TirYWxN2EUzpkTHYZhJAwccpMdecyVqxtIQ6YOHLOmBCVNUywjyAHQM5dFCECohanhr41FF3xfNGDkEewCVhCZuEiGC3WwhmhjmITydgU9ohxekqaTDtkHnS7bXz0syjq3XuMjTuQY144/+KYiDsd+nZ8MECQ+dMNkZRUWf5o+qH9B02Bg+tsqoQoel52mLi8SUhAOoxczsCwPdhtbmiTAfuZ1/pwVvgu32+8IcSc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
